version: '3'

services:
 database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
 cars:
    container_name: cars
    build: ./cars
    ports:
      - "8080:80"
    networks:
      - app-network

 parts:
    container_name: parts
    build: ./parts
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
 app-network:
    driver: bridge