version: '3'

services:
 database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
 cars:
    container_name: cars
    build: ./cars
    ports:
      - "8080:80"
    networks:
      - app-network

 parts:
    container_name: parts
    build: ./parts
    ports:
      - "8081:80"
    networks:
      - app-network
 keycloak:
   image: quay.io/keycloak/keycloak:23.0.6
   ports:
     - "8180:8080"
   volumes:
     - ./keycloak:/opt/keycloak/data/import
   container_name: keycloak
   networks:
     - app-network
   command: -v start-dev
   environment:
     KEYCLOAK_ADMIN: admin
     KEYCLOAK_ADMIN_PASSWORD: 12345



networks:
 app-network:
    driver: bridge